/**
 * Lessico concettuale offline italiano/inglese orientato a cataloghi personali.
 * Ogni gruppo rappresenta sinonimi dello stesso concetto; include forme comuni
 * perché i nomi file non passano da stemming linguistico o servizi esterni.
 */
export const SEARCH_LEXICON: readonly (readonly string[])[] = [
  // Fotografia, media e formati
  ['foto', 'fotografia', 'fotografie', 'photo', 'photos', 'picture', 'pictures', 'image', 'images'],
  ['fotocamera', 'fotocamere', 'camera', 'cameras'],
  ['obiettivo', 'obiettivi', 'lens', 'lenses'],
  ['ritratto', 'ritratti', 'portrait', 'portraits'],
  ['primo piano', 'primi piani', 'closeup', 'closeups', 'close up', 'close ups'],
  ['panorama', 'panorami', 'panorama', 'panoramas', 'landscape', 'landscapes'],
  ['macro', 'macrofotografia', 'macrophoto', 'macrophotography'],
  ['autoscatto', 'autoscatto', 'selfie', 'selfies'],
  ['scatto', 'scatti', 'shot', 'shots'],
  ['album', 'album fotografico', 'photo album'],
  ['archivio', 'archivi', 'archive', 'archives'],
  ['collezione', 'collezioni', 'collection', 'collections'],
  ['miniatura', 'miniature', 'thumbnail', 'thumbnails'],
  ['anteprima', 'anteprime', 'preview', 'previews'],
  ['originale', 'originali', 'original', 'originals'],
  ['modificato', 'modificata', 'modificati', 'edited', 'retouched'],
  ['bianco e nero', 'bianco nero', 'monocromatico', 'black and white', 'black white', 'monochrome'],
  ['colore', 'colori', 'colour', 'colours', 'color', 'colors'],
  ['video', 'filmato', 'filmati', 'movie', 'movies', 'clip', 'clips'],
  ['audio', 'suono', 'suoni', 'sound', 'sounds'],
  ['musica', 'music'],
  ['canzone', 'canzoni', 'song', 'songs', 'track', 'tracks'],
  ['registrazione', 'registrazioni', 'recording', 'recordings'],
  ['voce', 'voci', 'voice', 'voices'],
  ['podcast', 'podcasts'],
  ['raw', 'grezzo', 'grezzi', 'cr2', 'cr3', 'nef', 'arw', 'raf', 'orf', 'rw2', 'dng', 'pef'],
  ['jpeg', 'jpg', 'jpe'],
  ['tiff', 'tif'],
  ['heif', 'heic'],
  ['png'], ['webp'], ['avif'], ['bmp'], ['gif'],
  ['mp3', 'mpeg audio'], ['wav', 'wave'], ['flac', 'lossless'], ['aac', 'm4a'],
  ['film', 'pellicola', 'pellicole', 'film', 'films'],
  ['negativo', 'negativi', 'negative', 'negatives'],
  ['diapositiva', 'diapositive', 'slide', 'slides'],

  // Persone e famiglia
  ['persona', 'persone', 'person', 'people'],
  ['famiglia', 'famiglie', 'family', 'families'],
  ['genitore', 'genitori', 'parent', 'parents'],
  ['madre', 'mamma', 'mamme', 'mother', 'mom', 'mum', 'moms', 'mums'],
  ['padre', 'papa', 'papi', 'father', 'dad', 'dads'],
  ['figlio', 'figli', 'son', 'sons'],
  ['figlia', 'figlie', 'daughter', 'daughters'],
  ['fratello', 'fratelli', 'brother', 'brothers'],
  ['sorella', 'sorelle', 'sister', 'sisters'],
  ['nonno', 'nonni', 'grandfather', 'grandpa', 'grandparents'],
  ['nonna', 'nonne', 'grandmother', 'grandma', 'grandparents'],
  ['zio', 'zii', 'uncle', 'uncles'],
  ['zia', 'zie', 'aunt', 'aunts'],
  ['cugino', 'cugini', 'cousin', 'cousins'],
  ['cugina', 'cugine', 'cousin', 'cousins'],
  ['marito', 'mariti', 'husband', 'husbands'],
  ['moglie', 'mogli', 'wife', 'wives'],
  ['coppia', 'coppie', 'couple', 'couples'],
  ['bambino', 'bambini', 'child', 'children', 'kid', 'kids'],
  ['bambina', 'bambine', 'girl', 'girls'],
  ['ragazzo', 'ragazzi', 'boy', 'boys'],
  ['ragazza', 'ragazze', 'girl', 'girls'],
  ['neonato', 'neonata', 'neonati', 'baby', 'babies', 'newborn'],
  ['uomo', 'uomini', 'man', 'men'],
  ['donna', 'donne', 'woman', 'women'],
  ['amico', 'amici', 'friend', 'friends'],
  ['amica', 'amiche', 'friend', 'friends'],
  ['gruppo', 'gruppi', 'group', 'groups'],

  // Eventi e vita quotidiana
  ['compleanno', 'compleanni', 'birthday', 'birthdays'],
  ['matrimonio', 'matrimoni', 'wedding', 'weddings'],
  ['anniversario', 'anniversari', 'anniversary', 'anniversaries'],
  ['festa', 'feste', 'party', 'parties', 'celebration', 'celebrations'],
  ['cerimonia', 'cerimonie', 'ceremony', 'ceremonies'],
  ['battesimo', 'battesimi', 'baptism', 'christening'],
  ['laurea', 'lauree', 'graduation', 'graduations'],
  ['natale', 'christmas', 'xmas'],
  ['pasqua', 'easter'],
  ['capodanno', 'new year', 'new years eve'],
  ['carnevale', 'carnival'],
  ['concerto', 'concerti', 'concert', 'concerts'],
  ['spettacolo', 'spettacoli', 'show', 'shows', 'performance', 'performances'],
  ['vacanza', 'vacanze', 'holiday', 'holidays', 'vacation', 'vacations'],
  ['viaggio', 'viaggi', 'travel', 'travels', 'trip', 'trips', 'journey', 'journeys'],
  ['lavoro', 'work', 'job'],
  ['scuola', 'scuole', 'school', 'schools'],
  ['ufficio', 'uffici', 'office', 'offices'],
  ['cena', 'cene', 'dinner', 'dinners'],
  ['pranzo', 'pranzi', 'lunch', 'lunches'],
  ['colazione', 'colazioni', 'breakfast', 'breakfasts'],
  ['picnic', 'picnic'],
  ['regalo', 'regali', 'gift', 'gifts', 'present', 'presents'],
  ['torta', 'torte', 'cake', 'cakes'],
  ['candela', 'candele', 'candle', 'candles'],
  ['ballo', 'balli', 'danza', 'danze', 'dance', 'dancing'],
  ['gioco', 'giochi', 'game', 'games', 'play'],
  ['sport', 'sports'],
  ['calcio', 'football', 'soccer'],
  ['nuoto', 'swimming'],
  ['corsa', 'running', 'race'],
  ['passeggiata', 'passeggiate', 'walk', 'walking'],

  // Natura, meteo e paesaggi
  ['mare', 'mari', 'sea', 'seas', 'ocean', 'oceans'],
  ['spiaggia', 'spiagge', 'beach', 'beaches'],
  ['costa', 'coste', 'coast', 'coasts', 'shore', 'shores'],
  ['isola', 'isole', 'island', 'islands'],
  ['lago', 'laghi', 'lake', 'lakes'],
  ['fiume', 'fiumi', 'river', 'rivers'],
  ['ruscello', 'ruscelli', 'stream', 'streams', 'creek', 'creeks'],
  ['cascata', 'cascate', 'waterfall', 'waterfalls'],
  ['montagna', 'montagne', 'mountain', 'mountains'],
  ['collina', 'colline', 'hill', 'hills'],
  ['valle', 'valli', 'valley', 'valleys'],
  ['bosco', 'boschi', 'forest', 'forests', 'woods'],
  ['albero', 'alberi', 'tree', 'trees'],
  ['fiore', 'fiori', 'flower', 'flowers'],
  ['pianta', 'piante', 'plant', 'plants'],
  ['erba', 'grass'],
  ['campo', 'campi', 'field', 'fields'],
  ['giardino', 'giardini', 'garden', 'gardens'],
  ['parco', 'parchi', 'park', 'parks'],
  ['deserto', 'deserti', 'desert', 'deserts'],
  ['roccia', 'rocce', 'rock', 'rocks'],
  ['cielo', 'sky', 'skies'],
  ['nuvola', 'nuvole', 'cloud', 'clouds', 'cloudy'],
  ['sole', 'sun', 'sunny'],
  ['luna', 'moon'],
  ['stella', 'stelle', 'star', 'stars'],
  ['tramonto', 'tramonti', 'sunset', 'sunsets'],
  ['alba', 'albe', 'sunrise', 'sunrises', 'dawn'],
  ['notte', 'notti', 'night', 'nights'],
  ['giorno', 'giorni', 'day', 'days', 'daytime'],
  ['mattina', 'mattine', 'morning', 'mornings'],
  ['sera', 'sere', 'evening', 'evenings'],
  ['pioggia', 'rain', 'rainy'],
  ['neve', 'snow', 'snowy', 'innevato', 'innevata', 'innevati', 'innevate'],
  ['nebbia', 'fog', 'foggy', 'mist'],
  ['temporale', 'temporali', 'storm', 'storms'],
  ['vento', 'wind', 'windy'],
  ['arcobaleno', 'arcobaleni', 'rainbow', 'rainbows'],
  ['primavera', 'spring'],
  ['estate', 'summer'],
  ['autunno', 'autumn', 'fall'],
  ['inverno', 'winter'],

  // Animali
  ['animale', 'animali', 'animal', 'animals'],
  ['cane', 'cani', 'dog', 'dogs'],
  ['gatto', 'gatti', 'cat', 'cats'],
  ['uccello', 'uccelli', 'bird', 'birds'],
  ['pesce', 'pesci', 'fish', 'fishes'],
  ['cavallo', 'cavalli', 'horse', 'horses'],
  ['mucca', 'mucche', 'cow', 'cows', 'cattle'],
  ['pecora', 'pecore', 'sheep'],
  ['capra', 'capre', 'goat', 'goats'],
  ['farfalla', 'farfalle', 'butterfly', 'butterflies'],
  ['ape', 'api', 'bee', 'bees'],
  ['leone', 'leoni', 'lion', 'lions'],
  ['tigre', 'tigri', 'tiger', 'tigers'],
  ['elefante', 'elefanti', 'elephant', 'elephants'],
  ['orso', 'orsi', 'bear', 'bears'],
  ['delfino', 'delfini', 'dolphin', 'dolphins'],

  // Luoghi, edifici e oggetti
  ['casa', 'case', 'home', 'homes', 'house', 'houses'],
  ['stanza', 'stanze', 'room', 'rooms'],
  ['cucina', 'cucine', 'kitchen', 'kitchens'],
  ['camera da letto', 'camere da letto', 'bedroom', 'bedrooms'],
  ['balcone', 'balconi', 'balcony', 'balconies'],
  ['porta', 'porte', 'door', 'doors'],
  ['finestra', 'finestre', 'window', 'windows'],
  ['tavolo', 'tavoli', 'table', 'tables'],
  ['sedia', 'sedie', 'chair', 'chairs'],
  ['letto', 'letti', 'bed', 'beds'],
  ['libro', 'libri', 'book', 'books'],
  ['telefono', 'telefoni', 'phone', 'phones', 'smartphone'],
  ['computer', 'computers', 'pc', 'laptop'],
  ['citta', 'citta', 'city', 'cities', 'town', 'towns'],
  ['paese', 'paesi', 'village', 'villages', 'country'],
  ['strada', 'strade', 'street', 'streets', 'road', 'roads'],
  ['piazza', 'piazze', 'square', 'squares'],
  ['ponte', 'ponti', 'bridge', 'bridges'],
  ['chiesa', 'chiese', 'church', 'churches'],
  ['castello', 'castelli', 'castle', 'castles'],
  ['museo', 'musei', 'museum', 'museums'],
  ['monumento', 'monumenti', 'monument', 'monuments'],
  ['ristorante', 'ristoranti', 'restaurant', 'restaurants'],
  ['hotel', 'albergo', 'alberghi', 'hotels'],
  ['aeroporto', 'aeroporti', 'airport', 'airports'],
  ['stazione', 'stazioni', 'station', 'stations'],
  ['barca', 'barche', 'boat', 'boats', 'ship', 'ships', 'vessel', 'vessels'],
  ['auto', 'automobile', 'automobili', 'macchina', 'macchine', 'car', 'cars'],
  ['moto', 'motocicletta', 'motociclette', 'motorcycle', 'motorcycles', 'motorbike'],
  ['bicicletta', 'biciclette', 'bici', 'bike', 'bikes', 'bicycle', 'bicycles'],
  ['treno', 'treni', 'train', 'trains'],
  ['aereo', 'aerei', 'plane', 'planes', 'airplane', 'airplanes', 'aircraft'],
  ['autobus', 'bus', 'buses'],
  ['camion', 'truck', 'trucks'],

  // Colori
  ['rosso', 'rossa', 'rossi', 'rosse', 'red'],
  ['blu', 'azzurro', 'azzurra', 'blue'],
  ['verde', 'verdi', 'green'],
  ['giallo', 'gialla', 'gialli', 'gialle', 'yellow'],
  ['arancione', 'orange'],
  ['viola', 'purple', 'violet'],
  ['rosa', 'pink'],
  ['marrone', 'brown'],
  ['nero', 'nera', 'neri', 'nere', 'black'],
  ['bianco', 'bianca', 'bianchi', 'bianche', 'white'],
  ['grigio', 'grigia', 'grigi', 'grigie', 'gray', 'grey'],
  ['oro', 'dorato', 'dorata', 'gold', 'golden'],
  ['argento', 'argentato', 'argentata', 'silver'],

  // Azioni, qualità e stati utili nei nomi file
  ['correre', 'corre', 'correndo', 'run', 'running'],
  ['camminare', 'cammina', 'camminando', 'walk', 'walking'],
  ['volare', 'vola', 'volando', 'fly', 'flying'],
  ['saltare', 'salta', 'saltando', 'jump', 'jumping'],
  ['ridere', 'ride', 'ridendo', 'laugh', 'laughing'],
  ['sorridere', 'sorride', 'sorriso', 'smile', 'smiling'],
  ['mangiare', 'mangia', 'eating', 'eat'],
  ['bere', 'beve', 'drink', 'drinking'],
  ['dormire', 'dorme', 'sleep', 'sleeping'],
  ['nuovo', 'nuova', 'nuovi', 'nuove', 'new'],
  ['vecchio', 'vecchia', 'vecchi', 'vecchie', 'old'],
  ['preferito', 'preferita', 'preferiti', 'preferite', 'favorite', 'favorites', 'favourite', 'favourites'],
  ['migliore', 'migliori', 'best'],
  ['grande', 'grandi', 'big', 'large'],
  ['piccolo', 'piccola', 'piccoli', 'piccole', 'small', 'little'],
  ['felice', 'felici', 'happy'],
  ['triste', 'tristi', 'sad']
]
